# Site settings
title: 谷雨书苑
header-img: img/home-bg.jpg
email: valleyrain.org@gmail.com
description: "谷雨书苑是一个立足于美国旧金山硅谷，面向广大华人的，自发性的非盈利读书分享团体"
baseurl: "/www"
url: "http://valleyrain.org"
twitter_username: valleyrainbook
github_username:  valleyrain-org
facebook_username:  valleyrainbook

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
